plugins {
//    id("io.sentry.android.gradle") version "3.0.1"
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-android-extensions'
    id 'kotlin-kapt'
}

//sentry {
//    includeProguardMapping = true
//    autoUploadProguardMapping = true
//}

android {
    compileSdkVersion 36
    namespace "com.mckimquyen.barcodescanner"
    defaultConfig {
        applicationId "com.mckimquyen.barcodescanner"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 20251108
        versionName "2025.11.08"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.incremental": "true"]
            }
        }

        buildConfigField "boolean", "ERROR_REPORTS_ENABLED_BY_DEFAULT", "true"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11.toString()
        targetCompatibility = JavaVersion.VERSION_11.toString()
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    signingConfigs {
        release {
            storeFile file("keystore.jks")
            storePassword "27072000"
            keyAlias "mckimquyen"
            keyPassword "27072000"
            //mckimquyen
            //84
        }
    }

    buildTypes {
        debug {
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3940256099942544/6300978111\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3940256099942544/1033173712\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3940256099942544/9257395921\""
        }
        release {
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3612191981543807/9640819744\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3612191981543807/2420196462\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3612191981543807/3075411396\""

            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

//    flavorDimensions.add("market")
    flavorDimensions.add("type")
    productFlavors {
        dev {
            buildConfigField "Boolean", "build_debug", "true"
            dimension "type"
            buildConfigField("String", "FLAVOR_buildEnv", '"dev"')

//            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
//            resValue("string", "BANNER", "1cfc3df1cd94473a")
//            resValue("string", "INTER", "2f81cf4ca355cdac")
//            resValue("string", "EnableAdInter", "false")
//            resValue("string", "EnableAdBanner", "false")
        }
        production {
            buildConfigField "Boolean", "build_debug", "false"
            dimension "type"
            buildConfigField("String", "FLAVOR_buildEnv", '"prod"')

//            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
//            resValue("string", "BANNER", "1cfc3df1cd94473a")
//            resValue("string", "INTER", "2f81cf4ca355cdac")
//            resValue("string", "EnableAdInter", "true")
//            resValue("string", "EnableAdBanner", "true")
        }
    }

    buildFeatures {
//        compose = true
        viewBinding = true
        buildConfig = true
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.21"
    api 'androidx.core:core-ktx:1.13.1'
    api 'androidx.appcompat:appcompat:1.4.1'
    api 'com.google.android.material:material:1.5.0'
    api 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.multidex:multidex:2.0.1'
    //noinspection KaptUsageInsteadOfKsp
    kapt "androidx.room:room-compiler:2.6.1"
    api "androidx.room:room-runtime:2.6.1"
    api "androidx.room:room-rxjava2:2.6.1"
    api "android.arch.paging:runtime:1.0.1"
    api "android.arch.paging:rxjava2:1.0.1"
//    api 'com.budiyev.android:code-scanner:2.1.2'
    api 'com.github.yuriy-budiyev:code-scanner:2.3.2'
    api 'com.journeyapps:zxing-android-embedded:4.3.0'
    api 'com.googlecode.ez-vcard:ez-vcard:0.12.1'
    api "commons-codec:commons-codec:1.16.0"
    api "dev.turingcomplete:kotlin-onetimepassword:2.0.1"
    api "io.reactivex.rxjava2:rxkotlin:2.4.0"
    api "com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin:2.2.0"
//    api 'com.isseiaoki:simplecropview:1.1.8'
    api 'com.github.igreenwood:SimpleCropView:v1.1.6'
//    api 'com.github.florent37:singledateandtimepicker:2.2.6'
    api 'com.github.florent37:singledateandtimepicker:2.2.7'
//    api 'com.applovin:applovin-sdk:13.2.0'
    implementation("com.google.android.gms:play-services-ads:23.3.0")
    implementation("com.google.ads.mediation:applovin:13.0.0.0")
//    api 'io.sentry:sentry-android:7.8.0'
    implementation("com.google.android.play:review:2.0.1")
    implementation("com.google.android.play:review-ktx:2.0.1")
    debugImplementation("com.squareup.leakcanary:leakcanary-android:2.14")
}
